# Generated by Django 5.2.6 on 2025-09-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contatos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contato",
            new_name="Pessoa",
        ),
    ]
